Migrations and Seeder
lakovicj/laravel-example-vivify pull request #5
Opened 2020-11-12 15:05 UTC by lakovicj

2020-11-12 15:07 UTC, lakovicj commented
migrate:**refresh** VS migrate:**fresh**

- **refresh**: 
roll back all migrations and then execute migrate command

- **fresh**: 
drop all tables and then execute migrate command

The difference is that **fresh** command does not require up & down methods -> instead of down it automatically drops all the tables, and instead of up it creates tables. On the other hand, **refresh** gives you responsibility to implement up & down functionalities.

2020-11-16 08:40 UTC, dejan-stokic requested changes

2020-11-16 08:40 UTC, dejan-stokic commented on laravel-example/database/migrations/2020_11_12_133722_insert_new_column_users_table.php
> +            $table->drop('novo_polje');
@lakovicj Proveri ovaj deo, trenutno nece vratiti u prethodno stanje, nece obrisati kolonu.

2020-11-16 11:07 UTC, dejan-stokic approved these changes

2020-11-16 11:07 UTC, merged